version: '3.8'
services:
  cookingblog:
    image: cookingblog
    build:
      context: ./CookingBlog
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - Postgres__ConnectionString=Host=db;Port=5432;Database=cooking_db;Username=cooking_user;Password=cooking_pass;SearchPath=public;Pooling=true;
      - Postgres__Schema=public
      - Postgres__MigrationsEnable=true
      - ASPNETCORE_ENVIRONMENT=Development

  cookingblogfront:
    image: cookingblogfront
    build:
      context: ./CookingBlogFront
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cooking_db
      POSTGRES_USER: cooking_user
      POSTGRES_PASSWORD: cooking_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  

volumes:
  postgres_data:

networks:
  default:
    name: cooking_network