# Use the official ASP.NET Core image as the base image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

# Use the official ASP.NET Core SDK image for building
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CookingBlog/CookingBlog.csproj", "CookingBlog/"]
RUN dotnet restore "CookingBlog/CookingBlog.csproj"
COPY . .
WORKDIR "/src/CookingBlog"
RUN dotnet build "CookingBlog.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CookingBlog.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CookingBlog.dll"]
